#!/bin/sh

case "$1" in
    raise) brightnessctl set 5%+ > /dev/null ;;
    lower) brightnessctl set 5%- > /dev/null ;;
esac

CUR=$(brightnessctl get)
MAX=$(brightnessctl max)
PCT=$(( CUR * 100 / MAX ))

notify-send -h string:x-canonical-private-synchronous:brightness \
    -h int:value:"$PCT" -t 1500 -u low "Brightness: ${PCT}%"
