#!/bin/sh

LED=$(find /sys/class/leds -iname "*capslock*" | head -1)
STATE=$(cat "$LED/brightness" 2>/dev/null)

if [ "$STATE" = "1" ]; then
    notify-send -h string:x-canonical-private-synchronous:capslock -t 1000 -u low "Caps Lock ON"
else
    notify-send -h string:x-canonical-private-synchronous:capslock -t 1000 -u low "Caps Lock OFF"
fi
