#!/bin/sh

pactl set-source-mute @DEFAULT_SOURCE@ toggle
MUTED=$(pactl get-source-mute @DEFAULT_SOURCE@ | grep -o "yes\|no")

if [ "$MUTED" = "yes" ]; then
    notify-send -h string:x-canonical-private-synchronous:mic -t 1500 -u low "Mic Muted"
else
    notify-send -h string:x-canonical-private-synchronous:mic \
        -h int:value:100 -t 1500 -u low "Mic Unmuted"
fi
