# Kanagawa renk temasını dahil ediyoruz
include=~/.config/foot/kanagawa

font=Terminess Nerd Font Propo:size=14
font-bold=Terminess Nerd Font Mono:size=14:weight:bold
font-italic=Terminess Nerd Font Mono:size=14:slant=italic
font-bold-italic=Terminess Nerd Font Mono:size=14:weight=bold:slant=italic
