[als.time]
thresholds = { 0 = "night", 8 = "day", 18 = "night" }

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "wayland"

[output.backlight.predictor.manual]
thresholds.day = { 0 = 0, 100 = 10 }
thresholds.night = { 0 = 0, 100 = 60 }

[[output.ddcutil]]
name = "L27m-30 UPB67FNK LEN"
capturer = "wayland"
sleep_multiplier = 2.0
check_caps = false

[output.ddcutil.predictor.manual]
thresholds.day = { 0 = 0, 100 = 10 }
thresholds.night = { 0 = 0, 100 = 60 }

[[keyboard]]
name = "keyboard-thinkpad"
path = "/sys/bus/platform/devices/thinkpad_acpi/leds/tpacpi::kbd_backlight"
